name: saidaikouyakusu-test
on: [push]
jobs:
  test-saidaikouyakusu:
    runs-on: ubuntu-latest
    steps:
       - name: Checkout repository
         uses: actions/checkout@v4

       - name: Make saidaikouyakusu.sh executable
         run: chmod +x saidaikouyakusu.sh

       - name: Run saidaikouyakusu-test
         run: ./saidaikouyakusu-test.sh
